name: farmer_assistant_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  provider: ^5.0.0                          #USED FOR STATE MANAGEMENT IN OUR APP
  dots_indicator: ^2.0.0                    #USED FOR  THE WORM DESIGN LIKE INDICATOR  
  smooth_page_indicator: ^0.2.3
  # flutter_rating_bar: ^3.0.1+1            #USED FOR RATING STARS
  modal_progress_hud_nsn: 0.1.0-nullsafety-1              #USED FOR ASYNCHRONOUS PURPOSES
#   shared_preferences: ^0.5.12+2
  firebase_core: ^1.2.1
  # firebase_database: ^6.0.0
#   firebase_auth: ^0.18.1+2
#   firebase_crashlytics: ^0.2.1+1
  cloud_firestore: ^2.0.0
  image_picker: ^0.8.0+1
  image_crop: ^0.4.0
  image_cropper: ^1.3.1
  tflite: ^1.1.2
  crop_your_image: ^0.5.1+1
#   dio: ^3.0.10
#   dio_http_cache: ^0.2.11
  get: ^4.1.4
  get_it: ^6.1.1
  fluid_bottom_nav_bar: ^1.3.0
  flutter_screenutil: any
  avatar_glow: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/static_assets/
    - assets/static_assets/bottom-nav-bar/
    # - assets/ml_assets/mobilenet_v1_1.0_224.txt
    # - assets/ml_assets/mobilenet_v1_1.0_224.tflite
    - assets/ml_assets/Peach_Labels.txt
    - assets/ml_assets/MobileNetV2_Peach.tflite
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
